call code --install-extension adamvoss.yaml 
call code --install-extension CoenraadS.bracket-pair-colorizer 
call code --install-extension dbaeumer.vscode-eslint 
call code --install-extension felixfbecker.php-debug 
call code --install-extension HookyQR.beautify 
call code --install-extension ikappas.phpcs 
call code --install-extension ilich8086.Untabify 
call code --install-extension oderwat.indent-rainbow 
call code --install-extension Sophisticode.php-formatter 
call code --install-extension tomesterez.style-vars-panel 
